name: "Fetch packages every day"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  fetch-packages:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: run fetch_packages script
        run: |
          python bin/fetch_packages.py
        env:
          GITHUB_USER: z3by
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
